const state={data:null,screen:null,performance:null,historyIndex:null,history:[],previous:null,filter:'ALL'};
const fmt=new Intl.NumberFormat('zh-TW',{maximumFractionDigits:2});
const moneyFmt=new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0});
const pctFmt=v=>v==null?'—':`${v>=0?'+':''}${fmt.format(v)}%`;
const xFmt=v=>v==null?'—':`${fmt.format(v)}x`;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function gradeClass(g){return g==='A'?'grade-a':g==='B'?'grade-b':'grade-c'}
function actionClass(a){return a==='BUY CANDIDATE'?'action-buy':a==='AVOID'?'action-block':'action-watch'}
function valueClass(v){return v==null?'':v>0?'positive':v<0?'negative':''}
function previousStock(ticker){return state.previous?.stocks?.find(s=>s.ticker===ticker)||null}
function rankMarkup(stock){const old=previousStock(stock.ticker);if(!old)return '<span class="rank-flat">—</span>';const d=old.rank-stock.rank;return d>0?`<span class="rank-up">↑${d}</span>`:d<0?`<span class="rank-down">↓${Math.abs(d)}</span>`:'<span class="rank-flat">—</span>'}
function currentAction(stock){return AlphaEngine.impliedAction(stock,state.data)}
function currentGate(stock){return AlphaEngine.buyGate(stock,state.data)}
function filteredStocks(){return state.data.stocks.filter(stock=>{const action=currentAction(stock);if(state.filter==='A')return stock.grade==='A';if(state.filter==='BUYABLE')return action==='BUY CANDIDATE';if(state.filter==='WATCH')return action==='WATCH'||action==='VERIFY';return true})}

function renderHeader(){const data=state.data;const ranked=[...data.stocks].sort((a,b)=>b.score-a.score);const top=ranked[0];const spreads=data.stocks.map(s=>({s,spread:AlphaEngine.alphaSpread(s,data.benchmark_asset)})).filter(x=>x.spread!=null).sort((a,b)=>b.spread-a.spread);document.querySelector('#topAlpha').textContent=`${top.ticker} ${top.name}`;document.querySelector('#topAlphaScore').textContent=`Alpha ${top.score} · Confidence ${top.confidence_score}`;if(spreads.length){document.querySelector('#topSpread').textContent=pctFmt(spreads[0].spread);document.querySelector('#topSpreadMeta').textContent=`${spreads[0].s.ticker} ${spreads[0].s.name} vs TSMC`}else{document.querySelector('#topSpread').textContent='待估值';document.querySelector('#topSpreadMeta').textContent='需要 TSMC + 候選股完整 FV'}document.querySelector('#buyGate').textContent=`≥ ${data.methodology.buy_gate}`;document.querySelector('#buyGateMeta').textContent=`Confidence ≥ ${data.decision_policy.min_confidence_score} · MOS ≥ ${data.decision_policy.min_margin_of_safety_pct}% · Spread ≥ ${data.decision_policy.min_alpha_spread_pct}%`;document.querySelector('#nextReview').textContent=`下一次 ${data.meta.next_review}`;const age=AlphaEngine.dateAgeDays(data.meta.market_data_as_of);const fresh=document.querySelector('#freshness');fresh.textContent=age>data.freshness_policy.market_max_calendar_days?`⚠ 市場資料 ${age} 天前`:`市場資料 ${data.meta.market_data_as_of}`;fresh.classList.toggle('stale',age>data.freshness_policy.market_max_calendar_days);const tags=[`Schema v${data.meta.schema_version}`,`Research ${data.meta.as_of}`,`Market ${data.meta.market_data_as_of}`,`History ${state.history.length}`,`Price freshness ≤${data.freshness_policy.market_max_calendar_days} calendar days`,`Fundamentals ≤${data.freshness_policy.fundamental_max_days} days`];document.querySelector('#dataMeta').innerHTML=tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}

function renderBenchmark(){const d=state.data,b=d.benchmark_asset,v=AlphaEngine.valuationMetrics(b),trigger=d.rotation_event.trigger_price,hit=b.reference_price>=trigger,progress=Math.min(100,b.reference_price/trigger*100);document.querySelector('#tsmcProgress').style.width=`${progress}%`;document.querySelector('#tsmcReference').textContent=`${b.ticker} ${b.name} ${fmt.format(b.reference_price)} / ${fmt.format(trigger)}（${b.reference_price_date}）`;document.querySelector('#tsmcExpectedReturn').textContent=`TSMC Expected Return：${pctFmt(v.expectedReturn)}`;const pill=document.querySelector('#tsmcPill');pill.textContent=hit?'事件已觸發':'事件未觸發';pill.className=`status-pill ${hit?'good':''}`;document.querySelector('#benchmarkGrid').innerHTML=[['Alpha Score',b.score??'VERIFY'],['Confidence',b.confidence_score??'VERIFY'],['Base Fair Value',b.valuation_model?.scenarios?.base?.fair_value?moneyFmt.format(b.valuation_model.scenarios.base.fair_value):'VERIFY'],['Expected Return',pctFmt(v.expectedReturn)]].map(([a,c])=>`<div class="metric-box"><span>${a}</span><strong>${c}</strong></div>`).join('')}

function renderTable(){document.querySelector('#rankingBody').innerHTML=filteredStocks().map(stock=>{const g=currentGate(stock),v=g.valuation,action=currentAction(stock);return `<tr><td>#${stock.rank}</td><td>${rankMarkup(stock)}</td><td class="company"><strong>${esc(stock.name)}</strong><span>${esc(stock.ticker)}</span></td><td class="score">${stock.score}</td><td>${stock.confidence_score}</td><td>${stock.reference_price==null?'—':fmt.format(stock.reference_price)}</td><td>${xFmt(v.forwardPE)}</td><td class="${valueClass(v.expectedReturn)}">${pctFmt(v.expectedReturn)}</td><td class="${valueClass(g.spread)}">${pctFmt(g.spread)}</td><td class="${valueClass(v.mos)}">${pctFmt(v.mos)}</td><td class="${actionClass(action)}"><strong>${action}</strong></td></tr>`}).join('');document.querySelector('#rankBaseline').textContent=state.previous?`週變動基準：${state.previous.meta.as_of}`:'目前只有基準 snapshot；下次週報後開始顯示排名變化。'}

function seriesFor(ticker){const map=new Map();state.history.forEach(s=>{const stock=s.stocks?.find(x=>x.ticker===ticker);if(stock)map.set(s.meta.as_of,{date:s.meta.as_of,score:stock.score,rank:stock.rank})});const current=state.data.stocks.find(x=>x.ticker===ticker);if(current)map.set(state.data.meta.as_of,{date:state.data.meta.as_of,score:current.score,rank:current.rank});return [...map.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(-52)}
function renderHistoryChart(ticker){const stock=state.data.stocks.find(s=>s.ticker===ticker),series=seriesFor(ticker),el=document.querySelector('#historyChart'),meta=document.querySelector('#historyMeta');if(!series.length){el.innerHTML='<div class="empty-state">尚無歷史資料</div>';return}const w=720,h=285,p={l:46,r:22,t:20,b:40},pw=w-p.l-p.r,ph=h-p.t-p.b,scores=series.map(x=>x.score);let min=Math.max(0,Math.floor(Math.min(...scores)/5)*5-5),max=Math.min(100,Math.ceil(Math.max(...scores)/5)*5+5);if(min===max){min-=5;max+=5}const x=i=>series.length===1?p.l+pw/2:p.l+i/(series.length-1)*pw,y=s=>p.t+(max-s)/(max-min)*ph;const grid=[min,Math.round((min+max)/2),max].map(v=>`<line x1="${p.l}" y1="${y(v)}" x2="${w-p.r}" y2="${y(v)}" class="chart-grid-line"/><text x="${p.l-8}" y="${y(v)+4}" class="chart-axis" text-anchor="end">${v}</text>`).join(''),pts=series.map((o,i)=>`${x(i)},${y(o.score)}`).join(' '),dots=series.map((o,i)=>`<circle cx="${x(i)}" cy="${y(o.score)}" r="5" class="chart-dot"><title>${o.date}: ${o.score}, #${o.rank}</title></circle>`).join('');el.innerHTML=`<svg viewBox="0 0 ${w} ${h}">${grid}<polyline points="${pts}" class="chart-line"/>${dots}<text x="${p.l}" y="${h-10}" class="chart-axis">${series[0].date}</text><text x="${w-p.r}" y="${h-10}" text-anchor="end" class="chart-axis">${series.at(-1).date}</text></svg>`;const delta=series.at(-1).score-series[0].score;meta.innerHTML=[`${stock.ticker} ${stock.name}`,`最新 ${series.at(-1).score}`,`期間 ${delta>=0?'+':''}${delta}`,`${series.length} 點`].map(x=>`<span class="tag">${esc(x)}</span>`).join('')}

function renderSelectors(){['historyTicker','scoreTicker','valuationTicker','evidenceTicker'].forEach(id=>{const s=document.querySelector(`#${id}`),old=s.value;s.innerHTML=state.data.stocks.map(x=>`<option value="${x.ticker}">${x.ticker} ${esc(x.name)}</option>`).join('');if(old&&state.data.stocks.some(x=>x.ticker===old))s.value=old});renderHistoryChart(document.querySelector('#historyTicker').value);renderScoreDecomposition(document.querySelector('#scoreTicker').value);renderValuation(document.querySelector('#valuationTicker').value);renderEvidence(document.querySelector('#evidenceTicker').value)}

function renderWeeklyChanges(){const el=document.querySelector('#weeklyChanges');if(!state.previous){el.innerHTML='<div class="empty-state">等待下一份 snapshot 建立閉環比較。</div>';return}const changes=[];state.data.stocks.forEach(s=>{const o=previousStock(s.ticker);if(!o){changes.push({type:'up',title:`${s.ticker} ${s.name}`,detail:'NEW'});return}const ds=s.score-o.score,dr=o.rank-s.rank;if(ds||dr||s.grade!==o.grade||currentAction(s)!==o.action){const p=[];if(dr)p.push(`Rank ${dr>0?'↑':'↓'}${Math.abs(dr)}`);if(ds)p.push(`Score ${ds>0?'+':''}${ds}`);if(s.grade!==o.grade)p.push(`${o.grade}→${s.grade}`);changes.push({type:ds>=0&&dr>=0?'up':'down',title:`${s.ticker} ${s.name}`,detail:p.join(' · ')})}});el.innerHTML=changes.length?changes.map(c=>`<div class="change-row ${c.type}"><strong>${esc(c.title)}</strong><small>${esc(c.detail)}</small></div>`).join(''):'<div class="empty-state">本週無變化。</div>'}

function renderScoreDecomposition(ticker){const s=state.data.stocks.find(x=>x.ticker===ticker);if(!s)return;const weights=state.data.methodology.weights,confW=state.data.confidence_methodology.weights;const alphaRows=Object.entries(s.factor_scores).map(([k,v])=>`<div class="factor-row"><span>${esc(k)}</span><div class="factor-track"><div class="factor-fill" style="width:${Math.min(100,v/(weights[k]||1)*100)}%"></div></div><strong>${v}/${weights[k]}</strong></div>`).join(''),penalties=Object.entries(s.penalties||{}).filter(([,v])=>v).map(([k,v])=>`<div class="factor-row penalty"><span>${esc(k)}</span><div class="factor-track"><div class="factor-fill" style="width:${Math.min(100,Math.abs(v)/20*100)}%"></div></div><strong>${v}</strong></div>`).join(''),conf=Object.entries(s.confidence_factors).map(([k,v])=>`<div class="factor-row"><span>Confidence · ${esc(k)}</span><div class="factor-track"><div class="factor-fill" style="width:${Math.min(100,v/(confW[k]||1)*100)}%"></div></div><strong>${v}/${confW[k]}</strong></div>`).join('');document.querySelector('#scoreDecomposition').innerHTML=`${alphaRows}${penalties}${conf}<div class="score-summary"><span class="tag">Alpha = ${AlphaEngine.alphaScore(s)}</span><span class="tag">Stored = ${s.score}</span><span class="tag">Confidence = ${AlphaEngine.confidenceScore(s)}</span><span class="tag">Provenance: ${esc(s.score_provenance)}</span></div>`}

function renderValuation(ticker){const s=state.data.stocks.find(x=>x.ticker===ticker);if(!s)return;const m=s.valuation_model||{},v=AlphaEngine.valuationMetrics(s),spread=AlphaEngine.alphaSpread(s,state.data.benchmark_asset);if(m.status!=='COMPLETE'){document.querySelector('#valuationModel').innerHTML=`<div class="verify-box"><strong>${esc(s.ticker)} ${esc(s.name)}：估值模型 ${esc(m.status||'VERIFY')}</strong><br>Forward EPS / normalized EPS / Bear-Base-Bull 尚未由第一手資料完整驗證，因此 Expected Return、MOS 與 Alpha Spread 不得拿來做換股決策。</div>`;return}const rows=['bear','base','bull'].map(k=>{const x=m.scenarios[k];return `<tr><td>${k.toUpperCase()}</td><td>${x.eps??'—'}</td><td>${x.multiple??'—'}x</td><td>${x.fair_value?moneyFmt.format(x.fair_value):'—'}</td><td>${x.probability??'—'}</td></tr>`}).join('');document.querySelector('#valuationModel').innerHTML=`<table class="valuation-table"><thead><tr><th>Scenario</th><th>EPS</th><th>Multiple</th><th>FV</th><th>Prob.</th></tr></thead><tbody>${rows}</tbody></table><div class="score-summary"><span class="tag">Forward PE ${xFmt(v.forwardPE)}</span><span class="tag">Normalized PE ${xFmt(v.normalizedPE)}</span><span class="tag">Expected Return ${pctFmt(v.expectedReturn)}</span><span class="tag">MOS ${pctFmt(v.mos)}</span><span class="tag">Spread ${pctFmt(spread)}</span></div>`}

function renderEvidence(ticker){const s=state.data.stocks.find(x=>x.ticker===ticker),ev=s?.evidence||[],el=document.querySelector('#evidenceList');if(!ev.length){el.innerHTML='<div class="empty-state">尚無 evidence。</div>';return}el.innerHTML=ev.map(e=>`<div class="evidence-row"><div class="evidence-main"><strong>${esc(e.metric)} · ${esc(e.value??'—')}</strong><span>${esc(e.period||'')} · observed ${esc(e.observed_at||'—')} · ${esc(e.status)}</span></div><small class="${e.quality==='FIRST_PARTY'?'quality-first':'quality-inferred'}">${esc(e.quality)} · ${e.source_url?`<a class="source-link" href="${esc(e.source_url)}" target="_blank" rel="noopener">${esc(e.source_type)} ↗</a>`:esc(e.source_type)}</small></div>`).join('')}

function renderCards(){document.querySelector('#stockCards').innerHTML=filteredStocks().map(s=>{const g=currentGate(s),v=g.valuation,a=currentAction(s),failed=Object.entries(g.checks).filter(([,ok])=>!ok).map(([k])=>k).join(', ')||'None';return `<article class="stock-card"><div class="card-top"><div><h3>${esc(s.name)}</h3><div class="ticker">${s.ticker} · ${a}</div></div><div><div class="big-score">${s.score}</div><span class="grade ${gradeClass(s.grade)}">${s.grade}</span></div></div><dl><dt>Confidence</dt><dd>${s.confidence_score}</dd><dt>Expected return / Spread</dt><dd>${pctFmt(v.expectedReturn)} / ${pctFmt(g.spread)}</dd><dt>Alpha thesis</dt><dd>${esc(s.thesis)}</dd><dt>Invalidation</dt><dd>${esc(s.invalidation_condition)}</dd><dt>Failed Gates</dt><dd>${esc(failed)}</dd><dt>Next verification</dt><dd>${esc(s.next_check)}</dd></dl></article>`}).join('')}

function renderMethodologies(){const alphaLabels={earnings_acceleration:'Earnings acceleration',revenue_quality:'Revenue quality',valuation:'Valuation',structural_catalyst:'Structural catalyst',balance_sheet_cash_flow:'Balance sheet / cash flow'};document.querySelector('#methodology').innerHTML=Object.entries(state.data.methodology.weights).map(([k,v])=>`<div class="method-row"><span>${alphaLabels[k]||esc(k)}</span><strong>${v}</strong></div>`).join('');const confLabels={evidence_quality:'Evidence quality',forecast_visibility:'Forecast visibility',circle_of_competence:'Circle of competence',thesis_clarity:'Thesis clarity',data_freshness:'Data freshness'};document.querySelector('#confidenceMethodology').innerHTML=Object.entries(state.data.confidence_methodology.weights).map(([k,v])=>`<div class="method-row"><span>${confLabels[k]||esc(k)}</span><strong>${v}</strong></div>`).join('')}

function renderAllocation(){const d=state.data,rot=AlphaEngine.rotationGate(d),capital=Math.max(0,Number(document.querySelector('#capitalInput').value)||d.rotation_model.capital_default);document.querySelector('#allocationMode').textContent=rot.allocations.mode;document.querySelector('#cashFloor').textContent=`${d.rotation_model.guardrails.cash_floor_pct}%`;const allocations=rot.allocations.allocations;let invested=0,cash=0;document.querySelector('#allocationList').innerHTML=allocations.map(a=>{const amount=capital*a.weight/100;if(a.ticker==='CASH'){cash+=amount;return `<div class="allocation-row"><strong>現金</strong><span>${fmt.format(a.weight)}%</span><span>${moneyFmt.format(amount)}</span><small>Liquidity reserve</small><small>—</small></div>`}invested+=amount;const s=d.stocks.find(x=>x.ticker===a.ticker),gate=currentGate(s),shares=s.reference_price?Math.floor(amount/s.reference_price):null,lots=shares==null?null:Math.floor(shares/1000);return `<div class="allocation-row"><strong>${a.ticker} ${esc(s.name)}</strong><span>${fmt.format(a.weight)}%</span><span>${moneyFmt.format(amount)}</span><small>${shares==null?'price VERIFY':`${fmt.format(shares)} 股 / ${lots} 張`}</small><small>Spread ${pctFmt(gate.spread)}</small></div>`}).join('');document.querySelector('#investedAmount').textContent=moneyFmt.format(invested);document.querySelector('#cashAmount').textContent=moneyFmt.format(cash);document.querySelector('#gateResult').textContent=rot.status;const pill=document.querySelector('#simulationStatus');pill.textContent=rot.status;pill.className=`status-pill ${rot.status.startsWith('READY')?'good':'bad'}`;document.querySelector('#allocationWarning').textContent=rot.reasons.join('；')||'所有 Gate 通過，仍需人工 Review。'}

function renderScreen(){const s=state.screen,el=document.querySelector('#screenStatus');if(!s){el.textContent='NO DATA';return}el.textContent=s.meta.status;el.className=`status-pill ${s.meta.status==='CURRENT'?'good':''}`;document.querySelector('#screenRules').innerHTML=Object.entries(s.rules).map(([k,v])=>`<div class="method-row"><span>${esc(k)}</span><strong>${esc(Array.isArray(v)?v.join(', '):v)}</strong></div>`).join('');document.querySelector('#screenCandidates').innerHTML=(s.candidates||[]).map(c=>`<div class="screen-row"><strong>${c.ticker} ${esc(c.name)}</strong><small>${esc(c.reason)} · ${esc(c.status)}</small></div>`).join('')||'<div class="empty-state">等待第一次 full-market screen。</div>'}
function renderPerformance(){const p=state.performance,el=document.querySelector('#calibrationStatus');if(!p){el.textContent='NO DATA';return}el.textContent=p.meta.status;el.className=`status-pill ${p.meta.status==='CALIBRATED'?'good':''}`;const rows=(p.horizons||[]).map(h=>`<div class="method-row"><span>${h.weeks}W excess return</span><strong>${h.sample_size?`${pctFmt(h.mean_excess_return_pct)} · n=${h.sample_size}`:'等待樣本'}</strong></div>`).join('');document.querySelector('#performanceSummary').innerHTML=`${rows}<p class="panel-note">目標：檢驗 Score bucket 是否能預測未來 excess return；樣本不足時禁止調參。</p>`}
function renderAll(){renderHeader();renderBenchmark();renderTable();renderSelectors();renderWeeklyChanges();renderCards();renderMethodologies();renderAllocation();renderScreen();renderPerformance()}
async function loadHistory(){try{state.historyIndex=await (await fetch(`data/history/index.json?v=${Date.now()}`,{cache:'no-store'})).json();const entries=(state.historyIndex.snapshots||[]).slice(-52);state.history=(await Promise.all(entries.map(async e=>{try{return await (await fetch(`${e.path}?v=${Date.now()}`,{cache:'no-store'})).json()}catch{return null}}))).filter(Boolean);state.previous=[...state.history].filter(s=>s.meta.as_of<state.data.meta.as_of).sort((a,b)=>b.meta.as_of.localeCompare(a.meta.as_of))[0]||null}catch{state.history=[];state.previous=null}}
async function init(){try{const [d,s,p]=await Promise.all([fetch(`data/alpha.json?v=${Date.now()}`,{cache:'no-store'}),fetch(`data/screen.json?v=${Date.now()}`,{cache:'no-store'}),fetch(`data/performance.json?v=${Date.now()}`,{cache:'no-store'})]);if(!d.ok)throw new Error(`alpha HTTP ${d.status}`);state.data=await d.json();state.screen=s.ok?await s.json():null;state.performance=p.ok?await p.json():null;await loadHistory();document.querySelector('#capitalInput').value=state.data.rotation_model.capital_default;renderAll()}catch(e){document.querySelector('#freshness').textContent=`載入失敗：${e.message}`;document.querySelector('#freshness').classList.add('stale')}}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderTable();renderCards()}));
document.querySelector('#historyTicker').addEventListener('change',e=>renderHistoryChart(e.target.value));document.querySelector('#scoreTicker').addEventListener('change',e=>renderScoreDecomposition(e.target.value));document.querySelector('#valuationTicker').addEventListener('change',e=>renderValuation(e.target.value));document.querySelector('#evidenceTicker').addEventListener('change',e=>renderEvidence(e.target.value));document.querySelector('#capitalInput').addEventListener('input',()=>renderAllocation());
init();
